### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bj-mcduck** [emberyvr/emberyvr-cli#1]
Opening this as our starting off point for creating a site to promote companies in Vancouver that are using Ember. I'm thinking we'd also have pages to link to our other stuff online (youtube, meetup, slack, twitter,  etc).

### Ideas

- Have a company page that displays companies in Vancouver
- Show companies on a map that tells you who is hiring by pin colour
- Allow companies to sign up to add their info to the site
- Make the code re-usable enough that other ember community teams can use this in their cities

### To do:

- [x] Setup [repo](https://github.com/emberyvr/emberyvr-api) for an API
- [x]  Setup repo for the frontend (this one)
- [x] Setup heroku apps for API (staging, and production?)
- [ ] Setup ember hosting (firebase? has free .com ssl)
- [x] Add a basic company model for the API and `api/v1` endpoint
- [x] Add matching models for the frontend
- [ ] Get a `.com` name?
